### ISSUE TITLE
Рекомендуемые настройки ProGuard?

### ISSUE THREAD

**Issue by kiberwolf** [VKCOM/vk-android-sdk#103]
При компиляции с включённым Proguard после авторизации вылетает ошибка, хотя сам access token благополучно получается. Какие настройки ProGuard использовать? Текущие:

-keep class com.vk.sdk.**
-keep interface com.vk.sdk.**

Лог ошибки:
STACK_TRACE = java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.***/com.***.***.DetailsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:212)
	at android.app.ActivityThread.main(ActivityThread.java:5135)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.vk.sdk.VKSdk.d(VKSdk.java:344)
	at com.vk.sdk.api.VKRequest.b(VKRequest.java:264)
	at com.vk.sdk.api.httpClient.VKHttpClient.a(VKHttpClient.java:126)
	at com.vk.sdk.api.VKRequest.c(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.d(VKRequest.java:315)
	at com.vk.sdk.api.VKRequest.e(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.a(VKRequest.java:234)
	at com.***.***.a.a(DetailsFragment.java:117)
	at com.***.***.a.a(DetailsFragment.java:104)
	at android.support.v4.app.Fragment.b(Fragment.java:1786)
	at android.support.v4.app.ak.a(FragmentManager.java:947)
	at android.support.v4.app.ak.a(FragmentManager.java:1126)
	at android.support.v4.app.ak.a(FragmentManager.java:1108)
	at android.support.v4.app.ak.k(FragmentManager.java:1917)
	at android.support.v4.app.ad.onStart(FragmentActivity.java:544)
	at com.***.***.DetailsActivity.onStart(DetailsActivity.java:49)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
	at android.app.Activity.performStart(Activity.java:5241)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2210)
	... 11 more
java.lang.NullPointerException
	at com.vk.sdk.VKSdk.d(VKSdk.java:344)
	at com.vk.sdk.api.VKRequest.b(VKRequest.java:264)
	at com.vk.sdk.api.httpClient.VKHttpClient.a(VKHttpClient.java:126)
	at com.vk.sdk.api.VKRequest.c(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.d(VKRequest.java:315)
	at com.vk.sdk.api.VKRequest.e(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.a(VKRequest.java:234)
	at com.***.***.a.a(DetailsFragment.java:117)
	at com.***.***.a.a(DetailsFragment.java:104)
	at android.support.v4.app.Fragment.b(Fragment.java:1786)
	at android.support.v4.app.ak.a(FragmentManager.java:947)
	at android.support.v4.app.ak.a(FragmentManager.java:1126)
	at android.support.v4.app.ak.a(FragmentManager.java:1108)
	at android.support.v4.app.ak.k(FragmentManager.java:1917)
	at android.support.v4.app.ad.onStart(FragmentActivity.java:544)
	at com.***.***.DetailsActivity.onStart(DetailsActivity.java:49)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
	at android.app.Activity.performStart(Activity.java:5241)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2210)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:212)
	at android.app.ActivityThread.main(ActivityThread.java:5135)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Dreddik** [comment]
Попробуйте рекомендации отсюда http://stackoverflow.com/a/14060144/1271424

**Comment by kiberwolf** [comment]
Перекомпилировал с настройками:
-keep class com.vk.sdk.** {
  *;
}
-keep interface com.vk.sdk.**

Но всё равно вылетает ошибка:

STACK_TRACE = java.lang.RuntimeException: Unable to start activity ComponentInfo{com.***.***/com.***.***.DetailsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1960)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1985)
	at android.app.ActivityThread.access$600(ActivityThread.java:127)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4476)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.vk.sdk.VKSdk.getAccessToken(VKSdk.java:344)
	at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:264)
	at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:126)
	at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:315)
	at com.vk.sdk.api.VKRequest.start(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.executeWithListener(VKRequest.java:234)
	at com.***.***.a.a(DetailsFragment.java:117)
	at com.***.***.a.onCreateView(DetailsFragment.java:104)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.ak.a(FragmentManager.java:947)
	at android.support.v4.app.ak.a(FragmentManager.java:1126)
	at android.support.v4.app.ak.a(FragmentManager.java:1108)
	at android.support.v4.app.ak.k(FragmentManager.java:1917)
	at android.support.v4.app.ad.onStart(FragmentActivity.java:544)
	at com.***.***.DetailsActivity.onStart(DetailsActivity.java:49)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1135)
	at android.app.Activity.performStart(Activity.java:4646)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1933)
	... 11 more
java.lang.NullPointerException
	at com.vk.sdk.VKSdk.getAccessToken(VKSdk.java:344)
	at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:264)
	at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:126)
	at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:315)
	at com.vk.sdk.api.VKRequest.start(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.executeWithListener(VKRequest.java:234)
	at com.***.***.a.a(DetailsFragment.java:117)
	at com.***.***.a.onCreateView(DetailsFragment.java:104)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.ak.a(FragmentManager.java:947)
	at android.support.v4.app.ak.a(FragmentManager.java:1126)
	at android.support.v4.app.ak.a(FragmentManager.java:1108)
	at android.support.v4.app.ak.k(FragmentManager.java:1917)
	at android.support.v4.app.ad.onStart(FragmentActivity.java:544)
	at com.***.***.DetailsActivity.onStart(DetailsActivity.java:49)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1135)
	at android.app.Activity.performStart(Activity.java:4646)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1933)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1985)
	at android.app.ActivityThread.access$600(ActivityThread.java:127)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4476)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by Dreddik** [comment]
Попробовал '-keep class com.vk.** { *; }'
Работает.

**Comment by kiberwolf** [comment]
Спасибо, попробую.
