### ISSUE TITLE
Exception в версии 1.3.9

### ISSUE THREAD

**Issue by kiberwolf** [VKCOM/vk-android-sdk#114]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
            at com.vk.sdk.api.VKRequest.getLang(VKRequest.java:550)
            at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:274)
            at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:127)
            at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
            at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:315)
            at com.vk.sdk.api.VKRequest.start(VKRequest.java:376)
            at com.vk.sdk.api.VKRequest.executeWithListener(VKRequest.java:234)
            at com.*.*.LikesFragment.getFriendsList(LikesFragment.java:216)
            at com.*.*.LikesFragment.onCreateView(LikesFragment.java:131)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1927)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at com.*.*.LikesActivity.onStart(LikesActivity.java:51)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke

**Comment by ray1984** [comment]
Вы добавили в LikesActivity инициализацию VKUIHelper?

@Override
protected void onCreate() {
    super.onCreate();
    VKUIHelper.onCreate(this);
}

@Override
protected void onResume() {
    super.onResume();
    VKUIHelper.onResume(this);
}

@Override
protected void onDestroy() {
    super.onDestroy();
    VKUIHelper.onDestroy(this);
}

**Comment by kiberwolf** [comment]
Спасибо, проблема решилась.

**Comment by ray1984** [comment]
@kiberwolf закройте тогда тикет
