### ISSUE TITLE
Crash in VKUIHelper.onActivityResult() method after authorization

### ISSUE THREAD

**Issue by Stenopolz** [VKCOM/vk-android-sdk#115]
Our customer with Xiaomi device has got a crash with such a stack trace:

java.lang.RuntimeException: Unable to resume activity {com.ktosomnoy.android/com.ktosomnoy.android.activities.LoginActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=-1, data=Intent { (has extras) }} to activity {com.ktosomnoy.android/com.ktosomnoy.android.activities.LoginActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2926)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=-1, data=Intent { (has extras) }} to activity {com.ktosomnoy.android/com.ktosomnoy.android.activities.LoginActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3515)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:371)
       at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:366)
       at com.vk.sdk.VKAccessToken.saveTokenToSharedPreferences(VKAccessToken.java:88)
       at com.vk.sdk.VKSdk.setAccessToken(VKSdk.java:334)
       at com.vk.sdk.VKSdk.checkAndSetToken(VKSdk.java:312)
       at com.vk.sdk.VKSdk.processActivityResult(VKSdk.java:275)
       at com.vk.sdk.VKUIHelper.onActivityResult(VKUIHelper.java:104)
       at com.ktosomnoy.android.activities.VKBaseActivity.onActivityResult(VKBaseActivity.java:55)
       at com.ktosomnoy.android.activities.LoginActivity.onActivityResult(LoginActivity.java:77)
       at android.app.Activity.dispatchActivityResult(Activity.java:5416)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3511)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.access$600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5322)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:848)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
       at dalvik.system.NativeStart.main(NativeStart.java)

I've got no steps to reproduce. But I think there is something wrong with the authorization flow.

**Comment by ray1984** [comment]
Firstly, update sdk-library. Secondary, check that you added that code in VKBaseActivity:
@Override
protected void onCreate() {
    super.onCreate();
    VKUIHelper.onCreate(this);
}

**Comment by Stenopolz** [comment]
I've added missing method and uptaded sdk to the newest version. Probably I followed some outdated integration tutorial. I'll notify you if the issue reproduces. Thank you much.
