### ISSUE TITLE
NPE onActivityResult

### ISSUE THREAD

**Issue by coralinejones1985** [VKCOM/vk-android-sdk#123]
Я видела закрытые подобные баги, но этот возник в версии com.vk:androidsdk:1.3.9. Отмечу, что также у меня присутствует этот код:
@Override
protected void onCreate() {
super.onCreate();
VKUIHelper.onCreate(this);
}

java.lang.RuntimeException: Unable to resume activity {com.wachanga.android/com.wachanga.android.activity.WelcomeActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=-1, data=Intent { (has extras) }} to activity {com.wachanga.android/com.wachanga.android.activity.WelcomeActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2444)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2472)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1986)
       at android.app.ActivityThread.access$600(ActivityThread.java:123)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=-1, data=Intent { (has extras) }} to activity {com.wachanga.android/com.wachanga.android.activity.WelcomeActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:2980)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2431)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2472)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1986)
       at android.app.ActivityThread.access$600(ActivityThread.java:123)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.vk.sdk.VKSdk.setAccessToken(VKSdk.java:329)
       at com.vk.sdk.VKSdk.checkAndSetToken(VKSdk.java:316)
       at com.vk.sdk.VKSdk.processActivityResult(VKSdk.java:275)
       at com.vk.sdk.VKUIHelper.onActivityResult(VKUIHelper.java:104)
       at com.wachanga.android.framework.social.networks.VkSocialNetwork.onActivityResult(VkSocialNetwork.java:138)
       at com.wachanga.android.framework.social.SocialNetworkManager.onActivityResult(SocialNetworkManager.java:83)
       at com.wachanga.android.activity.WelcomeActivity.onActivityResult(WelcomeActivity.java:137)
       at android.app.Activity.dispatchActivityResult(Activity.java:4649)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:2976)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2431)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2472)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1986)
       at android.app.ActivityThread.access$600(ActivityThread.java:123)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ray1984** [comment]
Кроме onCreate нужно добавить еще следующее:
```
@Override
    protected void onResume() {
        super.onResume();
        VKUIHelper.onResume(this);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        VKUIHelper.onDestroy(this);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        VKUIHelper.onActivityResult(this, requestCode, resultCode, data);
    }
```

**Comment by coralinejones1985** [comment]
Да, я знаю, все это есть.

**Comment by ray1984** [comment]
Судя по логу, в VkSdk нет instance. Вы выполнили где-нибудь com.vk.sdk.VKSdk#initialize(com.vk.sdk.VKSdkListener, java.lang.String)?

**Comment by coralinejones1985** [comment]
Да, в методе onCreate() сразу после строки VKUIHelper.onCreate(this);

**Comment by coralinejones1985** [comment]
Ошибка происходит не всегда, судя по всему.

**Comment by coralinejones1985** [comment]
Извините, пожалуйста, ошибка продолжает возникать несмотря на то, что все сделано как надо, так же повторная инициализация ничего не дает. Будет ли она исправлена с вашей стороны или нет?

**Comment by Dreddik** [comment]
Покопаюсь, постараюсь исправить

**Comment by coralinejones1985** [comment]
Спасибо большое

**Comment by Dreddik** [comment]
Проверьте в новой версии #134
