### ISSUE TITLE
ошибка RuntimeException Unable to resume activity при авторизации

### ISSUE THREAD

**Issue by AlexMercier** [VKCOM/vk-android-sdk#127]
Подскажите что можно сделать по следующей проблеме,
изредка в краш-репортах приходит отчёт об ошибке показанный ниже.
сразу скажу что все методы у меня есть(onCreate, onResume, onDestroy, onActivityResult) и как положено вызывают VKUIHelper.
версия либы последняя, ошибка пришла с девайса os 4.1.2.

к сведению, у меня лично авторизация проходит нормально, и отчет об этой ошибке приходит редко, где-то раз 10 на 1000 юзеров. то есть ошибка встречается не на всех девайсах.

````StackTrace: 
java.lang.RuntimeException: Unable to resume activity {com.gemteam.vkfeed/com.gemteam.vkfeed.Activities.ActivityLogin}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=0, data=null} to activity {com.gemteam.vkfeed/com.gemteam.vkfeed.Activities.ActivityLogin}: java.lang.NullPointerException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2583)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
at android.app.ActivityThread.access$600(ActivityThread.java:133)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4807)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:559)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=61992, result=0, data=null} to activity {com.gemteam.vkfeed/com.gemteam.vkfeed.Activities.ActivityLogin}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3149)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2570)
... 12 more
Caused by: java.lang.NullPointerException
at com.vk.sdk.VKSdk.setAccessTokenError(VKSdk.java:375)
at com.vk.sdk.VKSdk.processActivityResult(VKSdk.java:294)
at com.vk.sdk.VKUIHelper.onActivityResult(VKUIHelper.java:104)
at com.gemteam.vkfeed.Activities.ActivityLogin.onActivityResult(ActivityLogin.java:67)
at android.app.Activity.dispatchActivityResult(Activity.java:5364)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3145)
```
мой код onActivityResult
```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        VKUIHelper.onActivityResult(this, requestCode,resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }
```

**Comment by Dreddik** [comment]
Проверьте в новой версии #134
