### ISSUE TITLE
java.lang.RuntimeException: VKSdk.initialize(Context) must be call from Application#onCreate()

### ISSUE THREAD

**Issue by pochtar** [VKCOM/vk-android-sdk#156]
Вызываю

public class MainActivity extends FragmentActivity {
@Override
protected void onCreate(Bundle savedInstanceState) {

super.onCreate(savedInstanceState);
VKSdk.initialize(getApplicationContext());

...
}}

Возвращает java.lang.RuntimeException: VKSdk.initialize(Context) must be call from Application#onCreate()

Я использую Android Studio, а не Eclipse, единственный java-файл в проекте - это MainActivity.java!
(не считая BuildConfig.java и R.java, конечно же)

Ошибка:

08-24 21:09:09.511 4432-4432/com.squiri.squiri E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.squiri.squiri, PID: 4432
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.squiri.squiri/com.squiri.squiri.MainActivity}: java.lang.RuntimeException: VKSdk.initialize(Context) must be call from Application#onCreate()
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
at android.app.ActivityThread.access$800(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5388)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: VKSdk.initialize(Context) must be call from Application#onCreate()
at com.vk.sdk.VKSdk.initialize(VKSdk.java:136)
at com.squiri.squiri.MainActivity.onCreate(MainActivity.java:57)
at android.app.Activity.performCreate(Activity.java:5280)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
            at android.app.ActivityThread.access$800(ActivityThread.java:155)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5388)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
            at dalvik.system.NativeStart.main(Native Method)

P.S. Все необходимые Permissions проставлены, Activity в Manifest прописаны; FaceBook API при этом работает отлично.

**Comment by Lomovskiy** [comment]
Наследуй класс от класса Application и в своем классе переопредели метод onCreate();

**Comment by lxknvlk** [comment]
VKSdk.initialize(Context)  должен быть в MainApplication а не в MainActivity

**Comment by Lomovskiy** [comment]
<code>
public class Application extends android.app.Application {

    VKAccessTokenTracker vkAccessTokenTracker = new VKAccessTokenTracker() {
        @Override
        public void onVKAccessTokenChanged(@Nullable VKAccessToken oldToken, @Nullable VKAccessToken newToken) {
            if (newToken == null) {
                Toast.makeText(Application.this, "AccessToken invalidated", Toast.LENGTH_SHORT).show();
                Intent intent = new Intent(Application.this, LoginActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(intent);
            }
        }
    };

    @Override
    public void onCreate() {
        super.onCreate();
        vkAccessTokenTracker.startTracking();
        VKSdk.initialize(Application.this);
    }
}
</code>

**Comment by nanom1t** [comment]
Для чего нужен именно Application? Почему так сложно?
```
public static VKSdk initialize(Context ctx) {
        if (sCurrentAppId != 0) {
            return vkSdk;
        }

        if (!(ctx instanceof Application)) {
            if (ctx == null) {
                throw new NullPointerException("Application context cannot be null");
            } else {
                throw new RuntimeException("VKSdk.initialize(Context) must be call from Application#onCreate()");
            }
        } else {
            if (!hasInStack(Application.class, "onCreate")) {
                throw new RuntimeException("VKSdk.initialize(Context) must be call from Application#onCreate()");
            }
        }

        int appId = getIntResByName(ctx, SDK_APP_ID);
        if (appId == 0) {
            throw new RuntimeException("String <integer name=\"com_vk_sdk_AppId\">your_app_id</integer> did not find in your resources.xml");
        }

        return initialize(ctx, appId, getStringResByName(ctx, SDK_API_VERSION, VKSdkVersion.DEFAULT_API_VERSION));
    }
```
Facebook SDK работает без Application. Даже одноклассники не требуют этого - https://apiok.ru/dev/sdk/android.
