### ISSUE TITLE
OutOfMemoryError big file attachment

### ISSUE THREAD

**Issue by blackdigger** [VKCOM/vk-android-sdk#197]
When I try to upload big file (tried 150Mb document) the SDK gives me OOM. I guess, maximum allowed size could vary depending on device model.

java.lang.OutOfMemoryError
at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:63)
at libcore.net.http.RetryableOutputStream.<init>(RetryableOutputStream.java:35)
at libcore.net.http.HttpEngine.initRequestBodyOut(HttpEngine.java:354)
at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:302)
at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
at libcore.net.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
at libcore.net.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:281)
at com.vk.sdk.api.httpClient.VKHttpClient$VKHTTPRequest.createConnection(VKHttpClient.java:323)
at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:172)
at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:150)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)

possible related issues:
http://stackoverflow.com/questions/2082057/outputstream-outofmemoryerror-when-sending-http
http://stackoverflow.com/questions/32353466/multipartentitybuilder-to-send-data-from-android-httpurlconnection

**Comment by Dreddik** [comment]
There is no silver bullet. VK has no possibility to load files partially, excluding video. Documents not supported yet

**Comment by Miha-x64** [comment]
https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html#setChunkedStreamingMode%28int%29

**Comment by Dreddik** [comment]
@Miha-x64 

> Note, not all HTTP servers support this mode.

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version. Reopen if it can be reproduced.
