### ISSUE TITLE
Ошибка при логине на android 4.4.2

### ISSUE THREAD

**Issue by ShadyRover** [VKCOM/vk-android-sdk#200]
На всех устройствах работает замечательно за исключением android 4.4.2.
При авторизации exception Failure delivering result ResultInfo{who=null, request=10485, result=-1, data=null}
Но причем в OnResult во фрагменте заходит и даже получает email, но затем вылетает

` FATAL EXCEPTION: main
                                                                                Process: com.avtofriend.main.autofriend, PID: 31747
                                                                                java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10485, result=-1, data=null} to activity {com.avtofriend.main.autofriend/com.avtofriend.main.autofriend.ui.activity.SplashAndLoginActivity}: java.lang.NullPointerException
                                                                                    at android.app.ActivityThread.deliverResults(ActivityThread.java:3455)
                                                                                    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3498)
                                                                                    at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:212)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: java.lang.NullPointerException
                                                                                    at com.avtofriend.main.autofriend.ui.fragment.auth.AuthFragment$7.onResult(AuthFragment.java:450)
                                                                                    at com.avtofriend.main.autofriend.ui.fragment.auth.AuthFragment$7.onResult(AuthFragment.java:446)
                                                                                    at com.vk.sdk.VKSdk.onActivityResult(VKSdk.java:189)`

**Comment by nwalker** [comment]
Столкнулся с чем-то похожим, в onActivityResult приходило data = null.
Возможно релевантный вопрос на StackOverflow - http://stackoverflow.com/questions/16479886/onactivityresult-intent-data-is-always-null , мне самому не хватает знаний понять, аналогичная ли это ситуация. 
В принципе, проблема решилась передачей в VKSdk.onActivityResult нового пустого Intent - в случае ошибки теряется собственно ошибка, но это все же лучше крэша приложения.

**Comment by ShadyRover** [comment]
Я решил проблему: когда в onActivityResult приходит null, то это значит, что сработал callback VKTokenTracker, событие onTokenChanged

**Comment by mmotorniy** [comment]
if (!VKSdk.isLoggedIn()) {
            VKSdk.login(NavigationActivity.this, "scope=offline,audio");
        }
Может как то так?
