### ISSUE TITLE
Ошибка SDK Android 

### ISSUE THREAD

**Issue by imusg** [VKCOM/vk-android-sdk#201]
Коллеги, добрый день!

Пишу приложение с использованием Android SDK.

По непонятным мне причинам, на "ровном месте" возникает ошибка:
12-30 16:11:57.105 7068-7085/? E/vk: error java.lang.ClassNotFoundException: com.google.android.gms.ads.identifier.AdvertisingIdClient at java.lang.Class.classForName(Native Method)at java.lang.Class.forName(Class.java:217)at java.lang.Class.forName(Class.java:172)
at com.vk.sdk.payments.VKPaymentsServerSender.getDeviceId(VKPaymentsServerSender.java:323)at com.vk.sdk.payments.VKPaymentsServerSender.access$400(VKPaymentsServerSender.java:48) at com.vk.sdk.payments.VKPaymentsServerSender$2.run(VKPaymentsServerSender.java:250) at android.os.Handler.handleCallback(Handler.java:725)at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:153) at android.os.HandlerThread.run(HandlerThread.java:60) Caused by: java.lang.NoClassDefFoundError: com/google/android/gms/ads/identifier/AdvertisingIdClient at java.lang.Class.classForName(Native Method)  at java.lang.Class.forName(Class.java:217)  at java.lang.Class.forName(Class.java:172) at com.vk.sdk.payments.VKPaymentsServerSender.getDeviceId(VKPaymentsServerSender.java:323)  at com.vk.sdk.payments.VKPaymentsServerSender.access$400(VKPaymentsServerSender.java:48) at com.vk.sdk.payments.VKPaymentsServerSender$2.run(VKPaymentsServerSender.java:250)  at android.os.Handler.handleCallback(Handler.java:725)  at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:153) 
at android.os.HandlerThread.run(HandlerThread.java:60) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.identifier.AdvertisingIdClient" on path: DexPathList[dexElements=[zip file "/data/app/com.vk.vktestapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.vk.vktestapp-1, /vendor/lib, /system/lib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)at java.lang.ClassLoader.loadClass(ClassLoader.java:501) at java.lang.ClassLoader.loadClass(ClassLoader.java:461)at java.lang.Class.classForName(Native Method)  at java.lang.Class.forName(Class.java:217) at java.lang.Class.forName(Class.java:172) at com.vk.sdk.payments.VKPaymentsServerSender.getDeviceId(VKPaymentsServerSender.java:323) at com.vk.sdk.payments.VKPaymentsServerSender.access$400(VKPaymentsServerSender.java:48)  at com.vk.sdk.payments.VKPaymentsServerSender$2.run(VKPaymentsServerSender.java:250) at android.os.Handler.handleCallback(Handler.java:725) at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:153) at android.os.HandlerThread.run(HandlerThread.java:60) 

Что делать?

**Comment by dkostryukov** [comment]
необходимо подключить гугл сервисы

**Comment by TanyaDolgopolova** [comment]
Можете расписать подробнее какие сервисы нужны?
