### ISSUE TITLE
VKShareDialogBuilder Exception: You can not set Dialog's OnCancelListener or OnDismissListener

### ISSUE THREAD

**Issue by sierbrat** [VKCOM/vk-android-sdk#206]
API 15
Caused by: java.lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
                                                                           at android.app.DialogFragment.onActivityCreated(DialogFragment.java:474)
                                                                           at android.app.Fragment.performActivityCreated(Fragment.java:2061)

**Comment by yesiyang01** [comment]
Encountered the same issue. 
To resolve it: Checkout the source code. In VKShareDialogDelegate.class, near the end of onCreateDialog function, comment out result.setOnCancelListener.

**Comment by agent10** [comment]
Have the same issue

**Comment by alan-derua** [comment]
Same issue, not fixed yet
