### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41323030 is not valid; is your activity running?

### ISSUE THREAD

**Issue by IstiN** [VKCOM/vk-android-sdk#21]
http://crashes.to/s/16bdc5895de

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41323030 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:653)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:281)
       at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
       at com.vk.sdk.VKOpenAuthActivity$OAuthWebViewClient.onReceivedError(VKOpenAuthActivity.java:142)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:363)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mkk814** [comment]
http://www.cnblogs.com/awkflf11/p/5293267.html
