### ISSUE TITLE
VKShareDialog крешит приложение при попытке отправки содержимого

### ISSUE THREAD

**Issue by archiewahwah** [VKCOM/vk-android-sdk#246]
падает вот так

Process: com.legendarytanks, PID: 2408
                                                                  java.lang.IllegalStateException: Can't compress a recycled bitmap
                                                                      at android.graphics.Bitmap.checkRecycled(Bitmap.java:347)
                                                                      at android.graphics.Bitmap.compress(Bitmap.java:999)
                                                                      at com.vk.sdk.api.photo.VKUploadImage.getTmpFile(VKUploadImage.java:69)
                                                                      at com.vk.sdk.api.photo.VKUploadWallPhotoRequest.<init>(VKUploadWallPhotoRequest.java:61)
                                                                      at com.vk.sdk.dialogs.VKShareDialogDelegate$4.onClick(VKShareDialogDelegate.java:359)
                                                                      at android.view.View.performClick(View.java:4780)
                                                                      at android.view.View$PerformClick.run(View.java:19866)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by archiewahwah** [comment]
ошибка пропала после добавления в scope VKScope.PHOTOS
