### ISSUE TITLE
VKSdk.login(this, "email")  - NullPointerException: name == null

### ISSUE THREAD

**Issue by sirbralex** [VKCOM/vk-android-sdk#249]
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.vk.sdk.VKServiceActivity}: java.lang.NullPointerException: name == null
Caused by java.lang.NullPointerException: name == null
       at java.lang.Enum.valueOf(Enum.java:187)
       at com.vk.sdk.VKServiceActivity$VKServiceType.valueOf(VKServiceActivity.java:60)
       at com.vk.sdk.VKServiceActivity.getType(VKServiceActivity.java:124)
       at com.vk.sdk.VKServiceActivity.onCreate(VKServiceActivity.java:143)`

**Comment by dkostryukov** [comment]
@sirbralex Update your sdk version
