### ISSUE TITLE
VkHttpClient errors in different methods

### ISSUE THREAD

**Issue by KonstantinBerkow** [VKCOM/vk-android-sdk#292]
На многих устройствах с разными версиями прошивки случаются вот такие ошибки, причем это было и на прошлых версиях vk sdk.

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
       at com.android.okio.OkBuffer.write(OkBuffer.java:574)
       at com.android.okio.OkBuffer.read(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:433)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHTTPRequest.abort(VKHttpClient.java:267)
       at com.vk.sdk.api.httpClient.VKHttpClient$3.run(VKHttpClient.java:161)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Fatal Exception: java.lang.NullPointerException
       at com.android.okhttp.ConnectionPool.maybeShare(ConnectionPool.java:251)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:295)
       at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHTTPRequest.createConnection(VKHttpClient.java:316)
       at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167)
       at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
       at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Fatal Exception: java.lang.NullPointerException
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:136)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHttpResponse.<init>(VKHttpClient.java:337)
       at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167)
       at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
       at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference
       at com.android.okio.OkBuffer.write(OkBuffer.java:574)
       at com.android.okio.OkBuffer.read(OkBuffer.java:610)
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:807)
       at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
       at java.io.InputStream.read(InputStream.java:162)
       at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194)
       at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
       at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:140)
       at java.io.InputStream.read(InputStream.java:162)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHttpResponse.<init>(VKHttpClient.java:364)
       at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167)
       at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
       at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Fatal Exception: java.lang.IllegalStateException: closed
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:439)
       at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
       at libcore.io.Streams.readFully(Streams.java:81)
       at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:209)
       at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:106)
       at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHttpResponse.<init>(VKHttpClient.java:351)
       at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167)
       at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
       at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Возможно это связано с багами в прошивке, но проблемы возникают на самых разных версиях прошивок, от 4.1.2 до 5.1.1.
Самому воспроизвести на доступных устройствах баг не получилось. Может быть есть какой-то воркэрануд? Очень похоже что это связано с закрытием конекшена из другого треда.

**Comment by ilyaklyukin** [comment]
got on android sdk 1.6.8

  java.lang.NullPointerException 
                                          at com.vk.sdk.api.httpClient.VKMultipartEntity.getContentLength(VKMultipartEntity.java:63) 
                                          at com.vk.sdk.api.httpClient.VKHttpClient$VKHTTPRequest.createConnection(VKHttpClient.java:311) 
                                          at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167) 
                                          at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77) 
                                          at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147) 
                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                          at java.lang.Thread.run(Thread.java:841)

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
