### ISSUE TITLE
Login Fatal Error 

### ISSUE THREAD

**Issue by egorikem** [VKCOM/vk-android-sdk#337]
Добрый день! Версия SDK 1.6.8
ApplicationID прописан, диалог открывается, но по закрытию апка падает с логами
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: egorikem.iamfit, PID: 1609
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10485, result=-1, data=null} to activity {egorikem.iamfit/egorikem.iamfit.presentation.view.activities.LoginActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4925)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968)
                      at android.app.ActivityThread.access$1600(ActivityThread.java:222)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                      at egorikem.iamfit.presentation.view.activities.LoginActivity.onActivityResult(LoginActivity.kt)
                      at android.app.Activity.dispatchActivityResult(Activity.java:7137)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968) 
                      at android.app.ActivityThread.access$1600(ActivityThread.java:222) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:158) 
                      at android.app.ActivityThread.main(ActivityThread.java:7229) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```
**SDK проинициализирован**, весь activity код с вашего офф. сайта. **Написано на Kotlin-e**. Видимо где-то у вас @Nullable, который криво разворачивается.

**Comment by agaDeonix** [comment]
Вот  нашел решение
http://ru.stackoverflow.com/questions/611568/android-vk-sdk-%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D1%81-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B5%D0%B9
мне помогло

**Comment by egorikem** [comment]
@agaDeonix Как вы поменяли сигнатуру системной функции onActivityResult()?
