### ISSUE TITLE
NPE в обработке ответа VKUploadWallPhotoRequest внутри VKShareDialogDelegate

### ISSUE THREAD

**Issue by agent10** [VKCOM/vk-android-sdk#345]
`java.lang.NullPointerException: collection == null
                                                       at java.util.ArrayList.<init>(ArrayList.java:94)
                                                       at com.vk.sdk.api.model.VKList.<init>(VKList.java:77)
                                                       at com.vk.sdk.api.model.VKAttachments.<init>(VKAttachments.java:129)
                                                       at com.vk.sdk.dialogs.VKShareDialogDelegate$5$1.onComplete(VKShareDialogDelegate.java:370)
                                                       at com.vk.sdk.api.VKUploadBase$VKUploadOperation$1.onComplete(VKUploadBase.java:70)
                                                       at com.vk.sdk.api.VKUploadBase$VKUploadOperation$VKUploadRequestListener$1$1.onComplete(VKUploadBase.java:132)
                                                       at com.vk.sdk.api.VKRequest$3.run(VKRequest.java:482)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

Всё это из-за того, что parsedModel == null
`@Override
					public void onComplete(VKResponse response) {
						VKPhotoArray photos = (VKPhotoArray) response.parsedModel;
						VKAttachments attachments = new VKAttachments(photos);
						makePostWithAttachments(attachments);
					}`

**Comment by olegsm** [comment]
Используйте новую версию SDK.
