### ISSUE TITLE
login

### ISSUE THREAD

**Issue by ugar0ff** [VKCOM/vk-android-sdk#371]
Fatal Exception: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:245)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:128)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:110)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:221)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
       at com.vk.sdk.api.httpClient.VKHttpClient$VKHTTPRequest.createConnection(VKHttpClient.java:316)
       at com.vk.sdk.api.httpClient.VKHttpClient.execute(VKHttpClient.java:167)
       at com.vk.sdk.api.httpClient.VKHttpOperation.start(VKHttpOperation.java:77)
       at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:147)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

в манифесте стоят разрешения
android.permission.ACCESS_NETWORK_STATE
android.permission.ACCESS_WIFI_STATE
android.permission.INTERNET

**Comment by plaxin** [comment]
В манифесте разрешения-то стоят, а выданы ли разрешения приложению на устройстве?
_Начиная с Android 6-ой версии введены усиленные работы по контролю разрешений для приложения от пользователя._

**Comment by ugar0ff** [comment]
@plaxin Только эти разрешения относятся к Normal permissions группе, а не к Dangerous permissions и запрашивать отдельно разрешения нет необходимости https://developer.android.com/guide/topics/permissions/overview

**Comment by kolobchanin** [comment]
Непосредственно самому воспроизвести не удалось, но Crashlytics утверждает, что крэш имеет место быть. Падает только на девайсах с 4 и 5 версией ОС. Чаще всего это ZenFone 5 (A501CG) на 4.4.2, Xperia ZL (независимо от версии ОС) и HTC Onex X (тоже независимо от версии ОС).

**Comment by olegsm** [comment]
use new 2.0.2 version.
