### ISSUE TITLE
Crash при отмене авторизации

### ISSUE THREAD

**Issue by solareye** [VKCOM/vk-android-sdk#390]
Используется VK SDK version 2.0

При отмене авторизации (не важно, установлено приложение VK или нет) получаем

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=282, result=0, data=Intent { act=com.vk.auth-token (has extras) }} to activity {...feature.share.ui.ShareActivity}: java.lang.NumberFormatException: s == null
Caused by: java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.vk.api.sdk.auth.VKAccessToken.<init>(VKAccessToken.kt:44)
        at com.vk.api.sdk.auth.VKAuthManager.processResult(VKAuthManager.kt:100)
        at com.vk.api.sdk.auth.VKAuthManager.onActivityResult(VKAuthManager.kt:63)
        at com.vk.api.sdk.VK.onActivityResult(VK.kt:107)
        at ...feature.share.ui.sharemenu.ShareMenuFragment.onActivityResult(ShareMenuFragment.kt:357)
        at ....feature.share.ui.ShareActivity.onActivityResult(ShareActivity.kt:127)`

в классе VKAccessToken, а конкретно при
`init {
        this.userId = Integer.parseInt(params[USER_ID])
        ...
    }`

потому что нет никакого USER_ID, а только HashMap size 3: 
1) "error" -> "access_denied"
2)  "error_reason" -> "user_denied"
3) "error_description" -> "User%20denied%20your%20request"

Проверил Sample проект - то же самое.

**Comment by olegsm** [comment]
fixed in 2.02
