### ISSUE TITLE
SDK v2.3.0 crashes on request

### ISSUE THREAD

**Issue by RumataEstorish** [VKCOM/vk-android-sdk#465]
```  
java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/RequestBody$Companion; in class Lokhttp3/RequestBody; or its superclasses (declaration of 'okhttp3.RequestBody' ...
 at com.vk.api.sdk.okhttp.OkHttpExecutor.execute(OkHttpExecutor.kt:89)
        at com.vk.api.sdk.chain.MethodChainCall.runRequest(MethodChainCall.kt:74)
        at com.vk.api.sdk.chain.MethodChainCall.call(MethodChainCall.kt:71)
        at com.vk.api.sdk.chain.ValidationHandlerChainCall.call(ValidationHandlerChainCall.kt:38)
        at com.vk.api.sdk.chain.InvalidCredentialsObserverChainCall.callWithAuthCheck(InvalidCredentialsObserverChainCall.kt:41)
        at com.vk.api.sdk.chain.InvalidCredentialsObserverChainCall.call(InvalidCredentialsObserverChainCall.kt:37)
        at com.vk.api.sdk.chain.TooManyRequestRetryChainCall.call(TooManyRequestRetryChainCall.kt:40)
        at com.vk.api.sdk.chain.InternalErrorRetryChainCall.call(InternalErrorRetryChainCall.kt:47)
        at com.vk.api.sdk.VKApiManager.executeWithExceptionAdjust(VKApiManager.kt:113)
        at com.vk.api.sdk.VKApiManager.execute(VKApiManager.kt:75)
        at com.vk.api.sdk.requests.VKRequest.onExecute(VKRequest.kt:87)
        at com.vk.api.sdk.internal.ApiCommand.execute(ApiCommand.kt:46)
        at com.vk.api.sdk.VK.executeSync(VK.kt:191)
```
Reproduced with code:
```
    fun getUser(): Single<VKUser> =
            Single.fromCallable { VK.executeSync(VKUserRequest()) }
                    .subscribeOn(schedulers.io)
```

App min SDK is set to 18

Have following dependency because upper versions don't support minSdk 18:
```
    implementation ("com.squareup.okhttp3:okhttp"){
        version {
            strictly('3.12.12')
        }
    }
```

P.S. issue not reproduced with Vk sdk 2.2.4

**Comment by RumataEstorish** [comment]
Ok, minSdk is 21 since 2.4.0. Issue can be closed
