### ISSUE TITLE
groupsGetById request fails to execute

### ISSUE THREAD

**Issue by why8m** [VKCOM/vk-android-sdk#476]
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.vk.sdk.api.groups.GroupsService$groupsGetById$1.parseResponse(GroupsService.kt:782)
	at com.vk.sdk.api.groups.GroupsService$groupsGetById$1.parseResponse(GroupsService.kt:84)
	at com.vk.sdk.api.NewApiRequest.parseResponse(NewApiRequest.kt)
	at com.vk.sdk.api.NewApiRequest.parse(NewApiRequest.kt:40)
	at com.vk.api.sdk.chain.MethodChainCall.parseResult(MethodChainCall.kt:82)
	at com.vk.api.sdk.chain.MethodChainCall.runRequest(MethodChainCall.kt:74)
	at com.vk.api.sdk.chain.MethodChainCall.call(MethodChainCall.kt:71)
	at com.vk.api.sdk.chain.ValidationHandlerChainCall.call(ValidationHandlerChainCall.kt:38)
	at com.vk.api.sdk.chain.ApiMethodPriorityChainCall.call(ApiMethodPriorityChainCall.kt:28)
	at com.vk.api.sdk.chain.InvalidCredentialsObserverChainCall.callWithAuthCheck(InvalidCredentialsObserverChainCall.kt:41)
	at com.vk.api.sdk.chain.InvalidCredentialsObserverChainCall.call(InvalidCredentialsObserverChainCall.kt:37)
	at com.vk.api.sdk.chain.TooManyRequestRetryChainCall.call(TooManyRequestRetryChainCall.kt:40)
	at com.vk.api.sdk.chain.RateLimitReachedChainCall.call(RateLimitReachedChainCall.kt:36)
	at com.vk.api.sdk.chain.InternalErrorRetryChainCall.call(InternalErrorRetryChainCall.kt:47)
	at com.vk.api.sdk.VKApiManager.executeWithExceptionAdjust(VKApiManager.kt:136)
	at com.vk.api.sdk.VKApiManager.execute(VKApiManager.kt:92)
	at com.vk.api.sdk.requests.VKRequest.onExecute(VKRequest.kt:95)
	at com.vk.api.sdk.internal.ApiCommand.execute(ApiCommand.kt:46)
	at com.vk.api.sdk.VK.executeSync(VK.kt:190)
	at com.vk.api.sdk.VK$execute$1.run(VK.kt:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:163)
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:88)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 28 more

```

**Comment by Artemych** [comment]
Could you please provide more details? Request params or response json?

**Comment by why8m** [comment]
@Artemych Sure, my bad.

Here is the usage:
```java
GroupsService groupsService = new GroupsService();
ApiCommand<GroupsGetByIdResponse> request = groupsService.groupsGetById(
        null,
        "apiclub",
        Collections.singletonList(GroupsFields.DESCRIPTION)
);

VK.execute(request, new VKApiCallback<GroupsGetByIdResponse>() {
    @Override
    public void success(GroupsGetByIdResponse groupsGetByIdResponse) {
        Log.i(TAG, groupsGetByIdResponse.getGroups().toString());
    }

    @Override
    public void fail(@NonNull Exception e) {
        Log.e(TAG, Log.getStackTraceString(e));
    }
});
```

Response JSON:
```json
[
  {
    "id": 1,
    "name": "ВКонтакте API",
    "screen_name": "apiclub",
    "is_closed": 0,
    "type": "group",
    "photo_50": "https://sun6-22.userapi.com/s/v1/if1/04SDm6iX9Lb6SbdbdrfonC3AYNYcmeITh7qA2hWfqZHsm8Vzg1eAgFgEXj5r9hnX4tJGjxxh.jpg?size=50x50&quality=96&crop=20,20,560,560&ava=1",
    "photo_100": "https://sun6-22.userapi.com/s/v1/if1/-KtBexxCseHjbF2KHkGe39sIKDnFws1s2jZGoSyu6VVi60svhEBzHdFpxtSTMVnSjHhc_x0h.jpg?size=100x100&quality=96&crop=20,20,560,560&ava=1",
    "photo_200": "https://sun6-22.userapi.com/s/v1/if1/VzUDrhCC83ylOGINHBFS2Cy3ctu2s6mXr4KwuS_sEXNN0AJwoyrxRwHtFomuX6h9NALKDx0F.jpg?size=200x200&quality=96&crop=20,20,560,560&ava=1",
    "description": "Группа посвящена разработке приложений на основе платформы ВКонтакте API и всему, что с ней связано.\n\nAPI позволяет создавать интересные, интерактивные и популярные приложения. Встроенные средства монетизации позволяют приносить доход разработчикам приложений, начиная с первых дней запуска.\n\nЕсли у вас возник вопрос или проблема, связанная с приложениями, а не с их созданием - обратитесь в службу поддержки: https://vk.com/support?act=home. Там помогут, тут нет."
  }
]
```

**Comment by why8m** [comment]
Apparently no longer relevant in the newest SDK version (3.2.2) (originally was reproduced in v. 3.1.0).
A different interface for the response is now provided too. 
@Artemych You can close this.
