### ISSUE TITLE
3.3.0 первая попытка входа через веб вью после установки приложения заканчивается ошибкой

### ISSUE THREAD

**Issue by neikist** [VKCOM/vk-android-sdk#492]
Ошибка следующая
` E/VKAuthManager: Failed to get VK token
    java.lang.NullPointerException
        at com.vk.api.sdk.auth.VKAccessToken.<init>(VKAccessToken.kt:54)
        at com.vk.api.sdk.auth.VKAuthManager.processResult(VKAuthManager.kt:120)
        at com.vk.api.sdk.auth.VKAuthManager.onActivityResult(VKAuthManager.kt:81)
        at com.vk.api.sdk.VK.onActivityResult(VK.kt:164)
        at com.vk.api.sdk.VK.onActivityResult$default(VK.kt:157)`
Последующие попытки если не переустанавливать приложение проходят успешно.
Ошибка возвращается сразу после запуска активити, даже не доходит до отображения страницы с полями ввода логина и пароля.

**Comment by Anschutz1927** [comment]
Можно эту же ошибку повторить на 3.2.2 версии. Если стереть данные приложения, то первый запуск тоже почти всегда с этой ошибкой.

**Comment by kot331107** [comment]
+1 та же проблема

**Comment by Artemych** [comment]
Проверьте пожалуйста версию 3.5.0
