### ISSUE TITLE
Игроки жалуются на проблемы с авторизацией

### ISSUE THREAD

**Issue by duxedo** [VKCOM/vk-android-sdk#501]
Просто вылезает toast (мы сами toast-ы не используем) "Произошла ошибка авторизации". Заставляли игроков обновить версии приложения ВК, хрома, Android System WebView, ничего не помогает.

Игроки пишут:

"после нажатия на кнопку Войти, выберешь через ВКонтакт, то становится белый экран и крутится колёсико загрузки, но потом снова выскакивает ошибка"
"авторизация через вк не работает,а именно не погружается страница авторизации и выкидывает с неизвестной ошибкой."
"При запуске игры  несколько раз в день требует сохранение прогресса через ВК. Выскакивает надпись" сбой при отправке данных", но вход производится. Появляется моя аватарка на текущем уровне. Но спустя несколько часов, требует зайти через ВК снова."
"При авторизации через ВК приходится по несколько раз запрашивать код, потому что страница ввода кода откатывается к предыдущему шагу, пока я смотрю код в почте ВК."

Проверяли на нескольких версиях нашего приложения и локально проблема не воспроизводится
Так же проверяли на vksdk/sample при попытке логина на эмуляторе (Android 11 x86_64 1536MB Ram google play) через приложение вк иногода происходит падение, в logcat только, что хромиум не смог найти библиотеку
```
2021-11-17 02:23:56.318 ? E/d: execution error HttpRequestExecutor-Init
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user_de/0/com.google.android.gms/app_chimera/m/0000000b/CronetDynamite.apk!/lib/x86_64/libcronet.94.0.4606.61.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.chromium.net.impl.CronetLibraryLoader.a(:com.google.android.gms.dynamite_cronetdynamite@213918104@21.39.18 (150800-0):4)
        at org.chromium.net.impl.CronetUrlRequestContext.<init>(:com.google.android.gms.dynamite_cronetdynamite@213918104@21.39.18 (150800-0):6)
        at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(:com.google.android.gms.dynamite_cronetdynamite@213918104@21.39.18 (150800-0):2)
        at org.chromium.net.ExperimentalCronetEngine$Builder.build(ExperimentalCronetEngine.java:2)
        at np0.b.a(CronetEngineBuilder.kt:44)
        at qp0.b$a.h(CronetClient.kt:11)
        at qp0.b$a.c(CronetClient.kt:2)
        at np0.d$a.c(CronetKnetEngine.kt:1)
        at np0.d$b.a(CronetKnetEngine.kt:3)
        at com.vk.httpexecutor.core.knet.KnetExecutorProvider.e(KnetExecutorProvider.kt:21)
        at com.vk.httpexecutor.core.knet.KnetExecutorProvider.i(KnetExecutorProvider.kt:3)
        at com.vk.utils.network.HttpExecutorInitializer.u(HttpExecutorInitializer.kt:25)
        at com.vk.utils.network.HttpExecutorInitializer.t(HttpExecutorInitializer.kt:2)
        at com.vkontakte.android.VKApplication$onCreate$36.invoke(VKApplication.kt:2)
        at com.vkontakte.android.VKApplication$onCreate$36.invoke(VKApplication.kt:1)
        at x30.b$c.a(ParallelTaskRunner.kt:8)
        at x30.b$c.call(ParallelTaskRunner.kt:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at x30.b.f(ParallelTaskRunner.kt:1)
        at x30.b.h(ParallelTaskRunner.kt:2)
        at x30.b.a(Unknown Source:0)
        at x30.a.apply(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.parallel.a$b.onNext(ParallelMap.java:2)
        at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnSubscriber.run(ParallelRunOn.java:16)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:2)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.f(ExecutorScheduler.java:8)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:3)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Сообщение появляется в logcat всегда, не только когда падает. Иногда приложение падает целиком, иногда WelcomeActivity остается в мертвом таске в стеке задач, a залогиненый UserActivity открывается в новом таске
Версия приложения вк 7.1

**Comment by Artemych** [comment]
Скажите пожалуйста, какую версию sdk используете и можно ли попросить приложить полный adb logcat?
