### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException on sdk 1.6.7

### ISSUE THREAD

**Issue by yunfeng1213** [VKCOM/vk-android-sdk#534]
we receive a lot of crash as below, our sdk version is: com.vk:androidsdk:1.6.7,please fix it !

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at com.vk.sdk.util.VKUtil.explodeQueryString(VKUtil.java:72)
at com.vk.sdk.dialogs.VKOpenAuthDialog$OAuthWebViewClient.processUrl(VKOpenAuthDialog.java:157)
at com.vk.sdk.dialogs.VKOpenAuthDialog$OAuthWebViewClient.shouldOverrideUrlLoading(VKOpenAuthDialog.java:175)
at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:77)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:89)
at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
at android.os.MessageQueue.next(MessageQueue.java:331)
at android.os.Looper.loop(Looper.java:149)
at android.app.ActivityThread.main(ActivityThread.java:6651)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by zhangjianshuai** [comment]
have the same problem here.

**Comment by zhangjianshuai** [comment]
Upgrading the sdk solved my problem

**Comment by imsnow** [comment]
I have the same problem
Debugging
There is input string in methiod `explodeQueryString`:
access_token=some_token&expires_in=0&user_id=12345&email=some_email&state=

state is empty

**Comment by olegsm** [comment]
We don't support 1.6.7 version anymore. Please, try to migrate 3.0+ version.
