### ISSUE TITLE
VKRequest.getLang() throws NPE

### ISSUE THREAD

**Issue by asimaruk** [VKCOM/vk-android-sdk#89]
Here is crash log 
java.lang.NullPointerException
	at com.vk.sdk.api.VKRequest.getLang(VKRequest.java:548)
	at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:274)
	at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:127)
	at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:311)
	at com.vk.sdk.api.VKRequest.start(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.executeWithListener(VKRequest.java:234)
	at com.topface.topface.utils.social.AuthToken$3.execute(AuthToken.java:118)
	at com.topface.framework.utils.BackgroundThread.run(BackgroundThread.java:53)

**Comment by Dreddik** [comment]
Seems like SDK don't have context at the moment

**Comment by Dreddik** [comment]
Try calling this function of VKUIHelper before executing the request, passing the application context there.
https://github.com/VKCOM/vk-android-sdk/commit/75d435ac14a5d00c048766418f2d0daf869e9a4e#diff-109a350ed749ddbcea8990c5bd266031R133
