### ISSUE TITLE
Креш в методе getAccessToken

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-android-sdk#99]
В аналитики своего приложения вижу крэш у 10 пользователей.
Крэш происходит в методе om.vk.sdk.VKSdk.getAccessToken - переменная sInstance null.
Авторизация у меня происходит точно как в примере этого репозитория. Есть два активити, главный LoginActivity в котором происходит инициализация sdk и пересылка на PostsActivity в котором происходит запрос постов на котором и получается этот крэш.
Интеречно что открытие PostsActivity из LoginActivity происходит если метод VKSdk.wakeUpSession возвращает true, то есть инстанс существует, а во второй активити становиться нулем. Бага наблюдается на android 4.4.2 и 4.4.3.  В домашних условиях не удалось воспроизвести баг. Есть идеи?

LoginActivity:

```
public class LoginActivity extends FragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);
        VKUIHelper.onCreate(this);
        VKSdk.initialize(sdkListener, Config.get().vkAppId);
        if (VKSdk.wakeUpSession(this)) {
            startPostsActivity();
        } else {
           addLoginButton();
        }
   }

    private void startPostsActivity() {
        Intent i = new Intent(this, PostsActivity.class);
        startActivity(i);
        finish();
    }

}
```

Креш в PostsActivity
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mezhevikin.rnd/com.mezhevikin.rnd.activity.PostsActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2410)
	at android.app.ActivityThread.access$800(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5388)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.vk.sdk.VKSdk.getAccessToken(VKSdk.java:344)
	at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:264)
	at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:127)
	at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
	at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:309)
	at com.vk.sdk.api.VKRequest.start(VKRequest.java:376)
	at com.vk.sdk.api.VKRequest.executeWithListener(VKRequest.java:234)
	at com.mezhevikin.rnd.activity.PostsActivity.loadItems(PostsActivity.java:87)
	at com.mezhevikin.rnd.activity.PostsActivity.onCreate(PostsActivity.java:43)
	at android.app.Activity.performCreate(Activity.java:5280)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2322)
	... 11 more
```

**Comment by nullproduction** [comment]
Я возможно (точно не уверен из-за редкой воспроизводимости крэша) нашел проблему, я не вызывал методы VKUIHelper.onResume и VKUIHelper.onDestroy во всех активити, только в главном.
Сейчас поправил это и залил в стор.

**Comment by Dreddik** [comment]
Странно, получается, что при переходе в PostsActivity инстанс sdk уже умирает.

**Comment by nullproduction** [comment]
@Dreddik  так эти крэши могли быть из-за того что я в PostsActivity  не вызывал методы VKUIHelper.onResume и VKUIHelper.onDestroy?

**Comment by Dreddik** [comment]
Я думаю, что нет.
Возможно, что имеет место какое-то восстановление состояния приложения в PostsActivity, при этом SDK мёртв

**Comment by basnopisets** [comment]
Извините, что вклиниваюсь, у меня тоже происходит ошибка в этом месте:

`0	
java.lang.NullPointerException
1	
at com.vk.sdk.VKSdk.getAccessToken(VKSdk.java:343)
2	
at com.vk.sdk.api.VKRequest.getPreparedParameters(VKRequest.java:264)
3	
at com.vk.sdk.api.httpClient.VKHttpClient.requestWithVkRequest(VKHttpClient.java:127)
4	
at com.vk.sdk.api.VKRequest.getPreparedRequest(VKRequest.java:297)
5	
at com.vk.sdk.api.VKRequest.getOperation(VKRequest.java:315)
6	
at com.vk.sdk.api.photo.VKUploadPhotoBase$VKUploadImageOperation.start(VKUploadPhotoBase.java:161)
7	
at com.vk.sdk.api.httpClient.VKHttpClient$2.run(VKHttpClient.java:210)
8	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
9	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10	
at java.lang.Thread.run(Thread.java:848)`

**Comment by Dreddik** [comment]
Должно быть всё ок в последних версиях
